# Generated by Django 3.2.15 on 2022-10-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('request_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('send_like_interval', models.IntegerField(choices=[(5, 'Five Minute'), (10, 'Ten Minute'), (15, 'Fifteen Minute'), (20, 'Twenty Minute'), (30, 'Thirty Minute'), (60, 'One Hour')], default=30)),
                ('last_send_like_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
