# Generated by Django 3.2.16 on 2022-11-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_active',
        ),
    ]
