# Generated by Django 3.2.18 on 2023-03-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moegram_bot', '0003_instagrampost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='last_send_like_date',
            new_name='send_like_datetime',
        ),
    ]
