# Generated by Django 3.2.18 on 2023-05-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moegram_bot', '0004_rename_last_send_like_date_telegramuser_send_like_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='send_like_interval',
            field=models.IntegerField(choices=[(0, 'Unlimited'), (1, 'One Minute'), (5, 'Five Minutes'), (10, 'Ten Minutes'), (15, 'Fifteen Minutes'), (20, 'Twenty Minutes'), (25, 'Twenty Five Minutes'), (30, 'Thirty Minutes'), (35, 'Thirty Five Minutes'), (40, 'Forty Minutes'), (45, 'Forty Five Minutes'), (50, 'Fifty Minutes'), (55, 'Fifty Five Minutes'), (60, 'Sixty Minutes'), (120, 'Two Hours')], default=120),
        ),
    ]
