# Generated by Django 3.2.20 on 2023-09-11 12:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter_video_downloader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "send_to",
                    models.CharField(
                        help_text="Should contain Telegram user id", max_length=25
                    ),
                ),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
